FROM petclinic/system AS build

COPY spring-petclinic/build.gradle spring-petclinic/settings.gradle spring-petclinic/gradlew ./
COPY spring-petclinic/gradle gradle
COPY spring-petclinic/src ./src

RUN sed -i 's/\r$//' gradlew && \
    chmod +x gradlew && \
    ./gradlew dependencies --no-daemon --info

RUN ./gradlew clean build -x test --no-daemon
