version: '3.8'

services:
  app:
    build: .
    environment:
      - SECRET_KEY=my_secret_key
      - ENV=development
      - DATABASE_URL=postgresql+psycopg2://user:password@db/mydb
      - FLASK_APP=urlshort
      - PATH="/home/appuser/.local/bin:$PATH"
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
