FROM petclinic/system AS build

COPY build.gradle settings.gradle gradlew ./
COPY gradle gradle
COPY src ./src

RUN sed -i 's/\r$//' gradlew && \
    chmod +x gradlew && \
    ./gradlew dependencies --no-daemon --info

RUN ./gradlew clean build -x test --no-daemon
